name: [Spring Boot Maven] Build, Test and Publish Docker Image

on:
  workflow_dispatch:
  push:
    branches:
      - 'springBootMaven'

jobs:

  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          path: "devops"

      - name: Build and Test Image
        run: docker-compose -f ./devops/devops/docker-compose.yml -p testing up --build --exit-code-from devops

      - name: Optimize and create Final Image
        run: docker build ./devops --tag ghcr.io/the-microservice-dungeon/devops/springbootmavenexample:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Final Image
        run: docker push ghcr.io/the-microservice-dungeon/devops/springbootmavenexample:latest