name: Maven - Build, Test and Publish Docker Image for Spring Boot with Maven

on:
  workflow_dispatch:
  push:
    branches:
      - 'springBootMaven'

jobs:

  build-test-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build and Test Image
        run: docker-compose -f devops/docker-compose.yml -p testing up --build --exit-code-from devops

      - name: Optimize and create Final Image
        run: docker build . -f devops/optimize.Dockerfile --tag ghcr.io/the-microservice-dungeon/devops/springbootmavenexample:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Final Image
        run: docker push ghcr.io/the-microservice-dungeon/devops/springbootmavenexample:latest

  deploy:
    needs: build-test-push
    runs-on: ubuntu-latest
    steps:
      - name: stop-pull-run
        uses: appleboy/ssh-action@master
        env:
          SERVICE_NAME: devops
        with:
          host: cides03.gm.fh-koeln.de
          username: ${{ secrets.PROD_USER }}
          password: ${{ secrets.PROD_PWD }}
          port: 22
          envs: SERVICE_NAME
          script: |
            echo ${{ secrets.PROD_PWD }} | sudo -S docker-compose -f $SERVICE_NAME/$SERVICE_NAMEService.yml pull
            echo ${{ secrets.PROD_PWD }} | sudo -S docker-compose -f $SERVICE_NAME/$SERVICE_NAMEService.yml up -d